spring.application.name=LuviFinancasPessoais

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/luvi_financas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Formato das datas no JSON
spring.jackson.serialization.write-dates-as-timestamps=false

# Porta
server.port=8080
