package br.com.luvi.financaspessoais.usuario.service;
import br.com.luvi.financaspessoais.usuario.entity.Usuario; import br.com.luvi.financaspessoais.usuario.repository.UsuarioRepository;
import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class UsuarioService {
 private final UsuarioRepository repo; private final PasswordEncoder encoder;
 public UsuarioService(UsuarioRepository r,PasswordEncoder e){repo=r;encoder=e;}
 @Transactional public Usuario cadastrar(String nome,String email,String senha){String e=normalizar(email);if(repo.existsByEmailIgnoreCase(e))throw new IllegalArgumentException("Este e-mail já está cadastrado.");if(senha==null||senha.length()<6)throw new IllegalArgumentException("A senha deve ter pelo menos 6 caracteres.");Usuario u=new Usuario();u.setNome(nome.trim());u.setEmail(e);u.setLogin(e);u.setSenha(encoder.encode(senha));u.setAuthProvider("LOCAL");return repo.save(u);}
 @Transactional public Usuario cadastrarOuVincularGoogle(String nome,String email,String subject){String e=normalizar(email);Usuario u=repo.findByEmailIgnoreCase(e).orElseGet(()->{Usuario n=new Usuario();n.setNome(nome==null||nome.isBlank()?e:nome.trim());n.setEmail(e);n.setLogin(e);n.setSenha(null);n.setAuthProvider("GOOGLE");return n;});if(u.getGoogleSubject()!=null&&!u.getGoogleSubject().equals(subject))throw new IllegalStateException("Este e-mail já está vinculado a outra conta Google.");u.setGoogleSubject(subject);if("LOCAL".equalsIgnoreCase(u.getAuthProvider()))u.setAuthProvider("LOCAL_GOOGLE");else if(u.getAuthProvider()==null||u.getAuthProvider().isBlank())u.setAuthProvider(u.getSenha()==null?"GOOGLE":"LOCAL_GOOGLE");return repo.save(u);}
 public Usuario atual(String login){return repo.findByLoginIgnoreCase(login).orElseGet(()->repo.findByEmailIgnoreCase(login).orElseThrow());}
 private String normalizar(String email){if(email==null||email.isBlank())throw new IllegalArgumentException("E-mail não informado.");return email.trim().toLowerCase();}
}