package br.com.luvi.financaspessoais.categoria.service;
import br.com.luvi.financaspessoais.categoria.dto.*; import br.com.luvi.financaspessoais.categoria.entity.Categoria; import br.com.luvi.financaspessoais.categoria.repository.CategoriaRepository;
import br.com.luvi.financaspessoais.grupo.repository.*; import br.com.luvi.financaspessoais.conta.service.ContaService; import br.com.luvi.financaspessoais.lancamento.enums.TipoLancamento; import br.com.luvi.financaspessoais.lancamento.repository.LancamentoRepository; import br.com.luvi.financaspessoais.usuario.entity.Usuario;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class CategoriaService{
 private final CategoriaRepository repo; private final GrupoRepository grupos; private final GrupoMembroRepository membros; private final LancamentoRepository lancamentos; private final ContaService contas;
 private static final Map<String,TipoLancamento> PADRAO=new LinkedHashMap<>(); static{PADRAO.put("Salário",TipoLancamento.RECEITA);PADRAO.put("Renda extra",TipoLancamento.RECEITA);PADRAO.put("Alimentação",TipoLancamento.DESPESA);PADRAO.put("Moradia",TipoLancamento.DESPESA);PADRAO.put("Transporte",TipoLancamento.DESPESA);PADRAO.put("Saúde",TipoLancamento.DESPESA);PADRAO.put("Educação",TipoLancamento.DESPESA);PADRAO.put("Lazer",TipoLancamento.DESPESA);PADRAO.put("Contas",TipoLancamento.DESPESA);PADRAO.put("Outros",TipoLancamento.DESPESA);}
 public CategoriaService(CategoriaRepository r,GrupoRepository g,GrupoMembroRepository m,LancamentoRepository l,ContaService cs){repo=r;grupos=g;membros=m;lancamentos=l;contas=cs;}
 private void validarGrupo(Long g,Usuario u){if(!membros.existsByGrupoIdAndUsuarioId(g,u.getId()))throw new SecurityException("Você não participa deste grupo.");}
 @Transactional public List<CategoriaResponse> listar(Long grupoId,Usuario u){garantirPadrao(grupoId,u);return (grupoId==null?repo.findByUsuarioIdOrderByNome(u.getId()):repo.findByGrupoIdOrderByNome(grupoId)).stream().map(CategoriaResponse::from).toList();}
 @Transactional public List<CategoriaResponse> listarPorConta(Long contaId,Usuario u){Long gid=contas.grupoCategorias(contaId,u);return listar(gid,u);}
 public void validarParaConta(Categoria c,Long contaId,Usuario u){Long gid=contas.grupoCategorias(contaId,u);if(gid==null){if(c.getGrupo()!=null||c.getUsuario()==null||!c.getUsuario().getId().equals(u.getId()))throw new IllegalStateException("Conta privada aceita somente categorias pessoais.");}else if(c.getGrupo()==null||!gid.equals(c.getGrupo().getId()))throw new IllegalStateException("A categoria selecionada não pertence ao grupo desta conta.");}
 @Transactional public CategoriaResponse criar(CategoriaRequest r,Usuario u){Categoria c=new Categoria();aplicar(c,r,u,true);return CategoriaResponse.from(repo.save(c));}
 @Transactional public CategoriaResponse atualizar(Long id,CategoriaRequest r,Usuario u){Categoria c=repo.findById(id).orElseThrow();validarDono(c,u);aplicar(c,r,u,false);return CategoriaResponse.from(repo.save(c));}
 @Transactional public CategoriaResponse alternar(Long id,Usuario u){Categoria c=repo.findById(id).orElseThrow();validarDono(c,u);c.setAtiva(!c.isAtiva());return CategoriaResponse.from(repo.save(c));}
 @Transactional public void excluir(Long id,Usuario u){Categoria c=repo.findById(id).orElseThrow();validarDono(c,u);if(lancamentos.existsByCategoriaId(id))throw new IllegalStateException("Esta categoria já possui lançamentos. Desative-a em vez de excluir.");repo.delete(c);}
 @Transactional(readOnly=true) public Categoria obter(Long id,Usuario u){Categoria c=repo.findById(id).orElseThrow(); if(c.getGrupo()!=null)validarGrupo(c.getGrupo().getId(),u); else if(c.getUsuario()==null||!c.getUsuario().getId().equals(u.getId()))throw new SecurityException("Categoria não permitida."); return c;}
 private void validarDono(Categoria c,Usuario u){if(c.getGrupo()!=null)validarGrupo(c.getGrupo().getId(),u);else if(c.getUsuario()==null||!c.getUsuario().getId().equals(u.getId()))throw new SecurityException("Categoria não permitida.");}
 private void aplicar(Categoria c,CategoriaRequest r,Usuario u,boolean novo){String n=r.nome().trim(); if(r.grupoId()!=null){validarGrupo(r.grupoId(),u);if(novo&&repo.existsByGrupoIdAndNomeIgnoreCase(r.grupoId(),n))throw new IllegalStateException("Já existe uma categoria com este nome no grupo.");c.setGrupo(grupos.findById(r.grupoId()).orElseThrow());c.setUsuario(null);}else{if(novo&&repo.existsByUsuarioIdAndNomeIgnoreCase(u.getId(),n))throw new IllegalStateException("Você já possui uma categoria com este nome.");c.setUsuario(u);c.setGrupo(null);}c.setNome(n);c.setTipo(r.tipo());}
 private void garantirPadrao(Long grupoId,Usuario u){if(grupoId!=null){validarGrupo(grupoId,u);if(!repo.findByGrupoIdOrderByNome(grupoId).isEmpty())return;var g=grupos.findById(grupoId).orElseThrow();PADRAO.forEach((n,t)->{Categoria c=new Categoria();c.setNome(n);c.setTipo(t);c.setGrupo(g);repo.save(c);});}else{if(!repo.findByUsuarioIdOrderByNome(u.getId()).isEmpty())return;PADRAO.forEach((n,t)->{Categoria c=new Categoria();c.setNome(n);c.setTipo(t);c.setUsuario(u);repo.save(c);});}}
}
